services:
  - type: web
    name: earnings-comparison-tool
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --threads 8 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MAX_UPLOAD_SIZE
        value: 300000000
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_CLOUD_STORAGE_BUCKET
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 2
