services:
  - type: web
    name: earnings-comparison-tool
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn wsgi:app 
      --bind 0.0.0.0:$PORT 
      --timeout 600 
      --workers 2 
      --threads 4 
      --worker-class gthread 
      --worker-tmp-dir /dev/shm 
      --max-requests 1000 
      --max-requests-jitter 50 
      --limit-request-line 0 
      --limit-request-field_size 0
      --limit-request-fields 0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MAX_UPLOAD_SIZE
        value: 300000000
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_CLOUD_STORAGE_BUCKET
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 2
